# Generated by Django 3.0.4 on 2020-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_auto_20200324_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feedback',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
