# Generated by Django 3.0.4 on 2020-03-29 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.RemoveField(
            model_name='user',
            name='feedback',
        ),
    ]
