# Generated by Django 3.0.4 on 2020-03-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_feedback_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='product',
        ),
    ]
