# Generated by Django 3.0.4 on 2020-03-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_auto_20200329_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='happy',
        ),
    ]
