# Generated by Django 3.0.4 on 2020-03-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_auto_20200329_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='feedback',
        ),
    ]
